name: Flutter App CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

env:
  FLUTTER_VERSION: "3.24.3"

jobs:
  flutter-tests:
    name: Flutter Tests & Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          cache: true

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Analyze Flutter code
        run: flutter analyze

      - name: Run Flutter tests
        run: flutter test --coverage

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: flutter-test-results
          path: |
            coverage/
            test/
          retention-days: 30

  build-flutter:
    name: Build Flutter Apps
    runs-on: ubuntu-latest
    needs: flutter-tests
    strategy:
      matrix:
        platform: [android, web]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          cache: true

      - name: Setup Java for Android
        if: matrix.platform == 'android'
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Build for Android
        if: matrix.platform == 'android'
        run: |
          flutter build apk --release

      - name: Build for Web
        if: matrix.platform == 'web'
        run: flutter build web --release

      - name: Upload Android artifacts
        if: matrix.platform == 'android'
        uses: actions/upload-artifact@v4
        with:
          name: android-builds
          path: build/app/outputs/flutter-apk/
          retention-days: 30

      - name: Upload Web artifacts
        if: matrix.platform == 'web'
        uses: actions/upload-artifact@v4
        with:
          name: web-build
          path: build/web/
          retention-days: 30

  deploy:
    name: Deploy Application
    runs-on: ubuntu-latest
    needs: [flutter-tests, build-flutter]
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download web build
        uses: actions/download-artifact@v4
        with:
          name: web-build
          path: build/web/

      - name: Deploy to production
        run: |
          echo "🚀 Deploying Flutter app..."
          echo "✅ Web build ready for deployment"
          echo "🌐 App available at production URL"
